@extends('layouts.portal')

@section('content')
<div class="module-header"><div><h1>Athlete Management</h1><p class="page-subtitle">Manage registered athletes and their sports participation</p></div></div>
@if (session('success'))<div class="notice">{{ session('success') }}</div>@endif
@if ($errors->any())<div class="notice notice-error">{{ $errors->first() }}</div>@endif
<div class="grid athlete-summary-grid"><div class="card stat"><small>Total Athletes</small><strong>{{ $summary['total'] }}</strong></div><div class="card stat"><small>Active Athletes</small><strong>{{ $summary['active'] }}</strong></div><div class="card stat"><small>Team Sport Athletes</small><strong>{{ $summary['team'] }}</strong></div><div class="card stat"><small>Individual Sport Athletes</small><strong>{{ $summary['individual'] }}</strong></div></div>
<section class="card athlete-filter-panel"><div class="section-heading"><div><h2>Find Athletes</h2><p class="meta">Search and filter registered athlete accounts.</p></div></div><form method="GET" action="{{ route('athletes.index') }}" class="athlete-filters"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search athlete..." aria-label="Search athlete"><select class="form-control" name="sport_id"><option value="">All Sports</option>@foreach ($sports as $sport)<option value="{{ $sport->id }}" @selected((string) request('sport_id') === (string) $sport->id)>{{ $sport->name }}</option>@endforeach</select><select class="form-control" name="grade"><option value="">All Grades</option>@foreach ($grades as $grade)<option value="{{ $grade }}" @selected(request('grade') === $grade)>{{ $grade }}</option>@endforeach</select><select class="form-control" name="gender"><option value="">All Genders</option>@foreach ($genders as $gender)<option value="{{ $gender }}" @selected(request('gender') === $gender)>{{ $gender }}</option>@endforeach</select><select class="form-control" name="status"><option value="">All Statuses</option>@foreach ($statuses as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ $status }}</option>@endforeach</select><select class="form-control" name="eligibility"><option value="">All Eligibility</option>@foreach ($eligibilities as $eligibility)<option value="{{ $eligibility }}" @selected(request('eligibility') === $eligibility)>{{ $eligibility }}</option>@endforeach</select><button class="button" type="submit">Search</button><a class="button button-muted" href="{{ route('athletes.index') }}">Reset</a></form></section>
<div class="card table-wrap athlete-table-wrap"><h2 class="panel-title">Athlete List</h2><table class="data-table athlete-table"><thead><tr><th>Athlete</th><th>Student ID</th><th>Grade</th><th>Sport</th><th>Coach</th><th>Eligibility</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse ($athletes as $athlete)@php($application = $athlete->applications->sortByDesc('created_at')->first())@php($medical = $athlete->medicalRecords->sortByDesc('examination_date')->first())@php($eligibility = $medical?->medical_status === 'Cleared' ? 'Eligible' : ($application?->status === 'Rejected' ? 'Not Eligible' : 'Pending'))<tr><td><strong>{{ $athlete->name }}</strong><br><small>{{ $athlete->username ?: $athlete->email }}</small></td><td>{{ $athlete->student_id ?: 'Not provided' }}</td><td>{{ $application?->grade ?: 'Not provided' }}</td><td>{{ $athlete->sport?->name ?? 'Unassigned' }}</td><td>{{ $athlete->sport?->coaches->pluck('name')->join(', ') ?: 'Unassigned' }}</td><td><span class="badge eligibility-{{ strtolower(str_replace(' ', '-', $eligibility)) }}">{{ $eligibility }}</span></td><td><span class="badge athlete-status-{{ strtolower($athlete->status) }}">{{ $athlete->status }}</span></td><td><div class="athlete-actions"><a class="text-link" href="{{ route('athletes.show', $athlete) }}">View</a><a class="text-link" href="{{ route('athletes.edit', $athlete) }}">Edit</a></div></td></tr>@empty<tr><td colspan="8" class="empty-cell"><strong>{{ request()->hasAny(['search', 'sport_id', 'grade', 'gender', 'status', 'eligibility']) ? 'No athletes match your search or filters.' : 'No athletes registered yet.' }}</strong>@if (request()->hasAny(['search', 'sport_id', 'grade', 'gender', 'status', 'eligibility']))<br><a class="button button-muted" href="{{ route('athletes.index') }}">Reset Filters</a>@endif</td></tr>@endforelse</tbody></table></div>
@endsection
