@extends('layouts.portal')

@section('content')
@php($application = $athlete->applications->sortByDesc('created_at')->first())
@php($medical = $athlete->medicalRecords->sortByDesc('examination_date')->first())
@php($eligibility = $medical?->medical_status === 'Cleared' ? 'Eligible' : ($application?->status === 'Rejected' ? 'Not Eligible' : 'Pending'))
<div class="module-header"><div><h1>{{ $athlete->name }}</h1><p class="page-subtitle">Athlete Profile</p></div><div class="event-header-actions"><a class="button button-secondary" href="{{ route('athletes.index') }}">Back</a><a class="button" href="{{ route('athletes.edit', $athlete) }}">Edit Athlete</a></div></div>
@if (session('success'))<div class="notice">{{ session('success') }}</div>@endif
<section class="athlete-detail-grid"><div class="card"><h2>Athlete Information</h2><div class="athlete-detail-list"><span><strong>Full Name</strong>{{ $athlete->name }}</span><span><strong>Student ID</strong>{{ $athlete->student_id ?: 'Not provided' }}</span><span><strong>Username</strong>{{ $athlete->username ?: 'Not provided' }}</span><span><strong>Email</strong>{{ $athlete->email }}</span><span><strong>Grade</strong>{{ $application?->grade ?: 'Not provided' }}</span><span><strong>Gender</strong>{{ $application?->gender ?: 'Not provided' }}</span><span><strong>Status</strong><em class="badge athlete-status-{{ strtolower($athlete->status) }}">{{ $athlete->status }}</em></span></div></div><div class="card"><h2>Sport Information</h2><div class="athlete-detail-list"><span><strong>Sport</strong>{{ $athlete->sport?->name ?? 'Unassigned' }}</span><span><strong>Classification</strong>{{ $athlete->sport?->classification ?? 'Not available' }}</span><span><strong>Assigned Coach</strong>{{ $athlete->sport?->coaches->pluck('name')->join(', ') ?: 'Unassigned' }}</span></div></div></section>
<div class="grid athlete-profile-stats"><div class="card stat"><small>Events</small><strong>{{ $athlete->attendanceRecords->pluck('event_id')->unique()->count() }}</strong><a class="text-link" href="{{ route('events.index', ['sport_id' => $athlete->sport_id]) }}">View events &rarr;</a></div><div class="card stat"><small>Applications</small><strong>{{ $athlete->applications->count() }}</strong><a class="text-link" href="{{ route('admin.applications', ['search' => $athlete->student_id ?: $athlete->name]) }}">View applications &rarr;</a></div><div class="card stat"><small>Attendance Records</small><strong>{{ $athlete->attendanceRecords->count() }}</strong><a class="text-link" href="{{ route('admin.attendance') }}">View attendance &rarr;</a></div><div class="card stat"><small>Eligibility</small><strong class="profile-eligibility-{{ strtolower(str_replace(' ', '-', $eligibility)) }}">{{ $eligibility }}</strong><a class="text-link" href="{{ route('admin.medical') }}">View medical &rarr;</a></div></div>
<section class="athlete-detail-grid"><div class="card"><h2>Eligibility and Medical</h2><div class="athlete-detail-list"><span><strong>Medical Clearance</strong>{{ $medical?->medical_status ?? 'Pending' }}</span><span><strong>Birth Certificate</strong>{{ $application?->birth_document_status ?? ($application?->birth_certificate_path ? 'Submitted' : 'Missing') }}</span><span><strong>Parent Consent</strong>{{ $application?->consent_document_status ?? ($application?->parent_consent_path ? 'Submitted' : 'Missing') }}</span><span><strong>Eligibility Status</strong>{{ $eligibility }}</span></div>@if ($medical)<div class="review-note"><strong>Medical findings</strong><p>{{ $medical->findings ?: 'No findings recorded.' }}</p><strong>Restrictions</strong><p>{{ $medical->restrictions ?: 'None recorded.' }}</p></div>@endif</div><div class="card"><h2>Recent Events</h2>@forelse ($athlete->attendanceRecords->sortByDesc('attended_on')->take(5) as $attendance)@if($attendance->event)<div class="related-row"><span><strong>{{ $attendance->event->title }}</strong><small>{{ $attendance->event->starts_at?->format('M j, Y g:i A') }} &middot; {{ $attendance->event->venue }}</small></span><span class="badge status-{{ strtolower($attendance->status) }}">{{ $attendance->status }}</span></div>@endif @empty<p class="empty-state">No event participation recorded.</p>@endforelse</div></section>
@endsection
