@extends('layouts.portal')
@section('content')
<div class="module-header"><div><h1>{{ $heading }}</h1><p class="page-subtitle">{{ $subtitle }}</p></div>@if($action)<a class="button" href="#">{{ $action }}</a>@endif</div>
@if($page === 'dashboard')<div class="grid grid-4">@foreach([['15','Total Sports'],['487','Active Athletes'],['12','Upcoming Events'],['8','Pending Applications']] as $stat)<div class="card stat"><strong>{{ $stat[0] }}</strong><small>{{ $stat[1] }}</small></div>@endforeach</div><div class="grid grid-2" style="margin-top:18px"><section class="card soft-card"><h2>Recent Activities</h2><div class="card list-card"><h3>New application received</h3><p>Juan Dela Cruz - Basketball</p></div><div class="card list-card"><h3>Event scheduled</h3><p>Regional Sports Meet - June 15, 2026</p></div></section><section class="card soft-card"><h2>Quick Actions</h2><a class="button report-button" href="{{ route('admin.applications') }}">Review Applications</a><a class="button report-button" href="{{ route('events.index') }}">Schedule Event</a></section></div>
@elseif($page === 'calendar')<div class="card calendar-card"><div class="calendar-toolbar"><button class="calendar-arrow" type="button" aria-label="Previous month">&larr;</button><h2>May 2026</h2><button class="calendar-arrow" type="button" aria-label="Next month">&rarr;</button></div><div class="calendar-grid calendar-weekdays"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span></div><div class="calendar-grid">@foreach(['','', '', '', '',1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31] as $day)<div class="calendar-day {{ in_array($day, [9,11,12,15,20,25]) ? 'has-event' : '' }}">{{ $day }}@if(in_array($day, [9,11,12,15,20,25]))<small></small>@endif</div>@endforeach</div><div class="calendar-legend"><span><i class="calendar-dot"></i> Scheduled event</span><span><i class="calendar-dot today-dot"></i> Today</span></div></div>
@elseif($page === 'applications')<div class="filters"><button class="button">All</button><button class="card">Pending 2</button><button class="card">Approved 1</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Student ID</th><th>Sport</th><th>Grade</th><th>Date</th><th>Status</th><th>Actions</th></tr></thead><tbody>@foreach([['Juan Dela Cruz','2026-0125','Basketball','Grade 11','Pending'],['Maria Santos','2026-0126','Volleyball','Grade 10','Pending'],['Pedro Reyes','2026-0127','Track and Field','Grade 12','Approved']] as $row)<tr>@foreach($row as $value)<td>{{ $value }}</td>@endforeach<td><button class="button">View</button></td></tr>@endforeach</tbody></table></div>
@elseif($page === 'sports')<div class="grid grid-3">@foreach(['Basketball','Volleyball','Track and Field','Badminton','Table Tennis','Chess'] as $sport)<div class="card list-card"><h3>{{ $sport }}</h3><p>Team Sport</p><div class="meta">Athletes <strong>{{ 38 + $loop->index * 9 }}</strong></div><div class="meta">Coach <strong>Coach Martinez</strong></div></div>@endforeach</div>
@elseif($page === 'athletes')<input class="form-control" style="max-width:300px;margin:16px 0" placeholder="Search by name or student ID"><div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Student ID</th><th>Sport</th><th>Grade</th><th>Status</th><th>Actions</th></tr></thead><tbody>@foreach([['Juan Dela Cruz','2026-0001','Basketball','Grade 11'],['Maria Santos','2026-0002','Volleyball','Grade 10'],['Pedro Reyes','2026-0003','Track and Field','Grade 12'],['Ana Garcia','2026-0004','Badminton','Grade 11']] as $row)<tr>@foreach($row as $value)<td>{{ $value }}</td>@endforeach<td><span class="badge status-present">Active</span></td><td>Edit &nbsp; Delete</td></tr>@endforeach</tbody></table></div>
@elseif($page === 'medical')<div class="grid grid-3"><div class="card stat"><span class="stat-icon">&#128137;</span><strong>42</strong><small>Cleared Athletes</small></div><div class="card stat"><span class="stat-icon">&#9888;</span><strong>5</strong><small>Pending Review</small></div><div class="card stat"><span class="stat-icon">&#128203;</span><strong>3</strong><small>Expiring This Month</small></div></div><div class="table-wrap" style="margin-top:18px"><table class="data-table"><thead><tr><th>Athlete</th><th>Student ID</th><th>Sport</th><th>Last Checkup</th><th>Clearance</th><th>Actions</th></tr></thead><tbody>@foreach([['Juan Dela Cruz','2026-0001','Basketball','May 2, 2026','Cleared'],['Maria Santos','2026-0002','Volleyball','April 26, 2026','Cleared'],['Pedro Reyes','2026-0003','Track and Field','April 18, 2026','Pending'],['Ana Garcia','2026-0004','Badminton','March 30, 2026','Expiring']] as $record)<tr>@foreach(array_slice($record, 0, 4) as $value)<td>{{ $value }}</td>@endforeach<td><span class="badge {{ $record[4] === 'Cleared' ? 'status-present' : 'status-absent' }}">{{ $record[4] }}</span></td><td><button class="button">View</button></td></tr>@endforeach</tbody></table></div>
@elseif($page === 'coaches')<div class="grid grid-3">@foreach([['RM','Coach Roberto Martinez','Basketball Coach'],['LS','Coach Linda Santos','Volleyball Coach'],['MR','Coach Mark Rivera','Track and Field Coach']] as $coach)<div class="card"><div style="display:flex;gap:12px;align-items:center"><div class="avatar">{{ $coach[0] }}</div><div><h3>{{ $coach[1] }}</h3><p class="meta">{{ $coach[2] }}</p></div></div><hr><p class="meta">&#9993; coach@snhhs.edu.ph<br>&#9742; +63 912 345 6789</p></div>@endforeach</div>
@elseif($page === 'events')@foreach(['Basketball Practice','Regional Sports Meet','Volleyball Training'] as $event)<div class="card list-card"><h3>{{ $event }}</h3><span class="badge">Training</span><div class="grid grid-3" style="margin-top:16px"><div class="meta">&#128197; May {{ 9 + $loop->index }}, 2026</div><div class="meta">&#9201; 3:00 PM - 5:00 PM</div><div class="meta">&#128205; Main Court</div></div></div>@endforeach
@elseif($page === 'attendance')<div class="grid grid-3"><div class="card"><label class="meta">Select Date</label><input class="form-control" value="May 8, 2026"></div><div class="card"><label class="meta">Select Event</label><select class="form-control"><option>Basketball Practice</option></select></div><div class="card soft-card"><small>Attendance Rate</small><strong>75%</strong></div></div><div class="table-wrap" style="margin-top:16px"><table class="data-table"><thead><tr><th>Name</th><th>Student ID</th><th>Attendance</th><th>Actions</th></tr></thead><tbody>@foreach(['Juan Dela Cruz','Maria Santos','Pedro Reyes','Ana Garcia'] as $name)<tr><td>{{ $name }}</td><td>2026-000{{ $loop->iteration }}</td><td><span class="badge {{ $loop->last ? 'status-absent' : 'status-present' }}">{{ $loop->last ? 'Absent' : 'Present' }}</span></td><td><button class="button">Mark Attendance</button></td></tr>@endforeach</tbody></table></div>
@elseif($page === 'announcements')@foreach($announcements as $announcement)<div class="card list-card"><h3>{{ $announcement[0] }} <span class="badge">Published</span></h3><p>{{ $announcement[2] }}</p><div class="meta">{{ $announcement[1] }}</div></div>@endforeach
@else<div class="grid grid-2">@foreach(['Athlete Participation Report','Attendance Summary','Sports Program Overview','Event Statistics'] as $report)<div class="card"><h3>{{ $report }}</h3><p class="meta">Comprehensive report and statistics for SNNHS activities.</p><button class="button report-button">Generate Report</button></div>@endforeach</div><div class="card" style="margin-top:16px"><h2>Participation Overview</h2><div class="chart"><div class="bar-col" style="height:75%"></div><div class="bar-col" style="height:55%"></div><div class="bar-col" style="height:85%"></div><div class="bar-col" style="height:45%"></div><div class="bar-col" style="height:65%"></div></div></div>@endif
@endsection
