@extends('layouts.portal')

@section('content')
<div class="module-header"><div><h1>Coach Management</h1><p class="page-subtitle">Manage coach records and assignments</p></div><a class="button" href="{{ route('coaches.create') }}">+ Add Coach</a></div>
@if (session('success'))<div class="notice">{{ session('success') }}</div>@endif
@if ($errors->any())<div class="notice notice-error">{{ $errors->first() }}</div>@endif
<div class="grid coach-summary-grid"><div class="card stat"><small>Total Coaches</small><strong>{{ $summary['total'] }}</strong></div><div class="card stat"><small>Active Coaches</small><strong>{{ $summary['active'] }}</strong></div><div class="card stat"><small>Head Coaches</small><strong>{{ $summary['head'] }}</strong></div><div class="card stat"><small>Assigned Athletes</small><strong>{{ $summary['athletes'] }}</strong></div></div>
<section class="card coach-filter-panel"><div class="section-heading"><div><h2>Find Coaches</h2><p class="meta">Search and filter coaching records.</p></div></div><form method="GET" action="{{ route('coaches.index') }}" class="coach-filters"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search coach..." aria-label="Search coach"><select class="form-control" name="sport_id"><option value="">All Sports</option>@foreach ($sports as $sport)<option value="{{ $sport->id }}" @selected((string) request('sport_id') === (string) $sport->id)>{{ $sport->name }}</option>@endforeach</select><select class="form-control" name="coach_type"><option value="">All Coach Types</option>@foreach ($coachTypes as $coachType)<option value="{{ $coachType }}" @selected(request('coach_type') === $coachType)>{{ $coachType }}</option>@endforeach</select><select class="form-control" name="status"><option value="">All Statuses</option>@foreach ($statuses as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ $status }}</option>@endforeach</select><button class="button" type="submit">Search</button><a class="button button-muted" href="{{ route('coaches.index') }}">Reset</a></form></section>
<div class="card table-wrap coach-table-wrap"><h2 class="panel-title">Coach List</h2><table class="data-table coach-table"><thead><tr><th>Coach</th><th>Specialty</th><th>Sport</th><th>Coach Type</th><th>Athletes</th><th>Upcoming Events</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse ($coaches as $coach)<tr><td><strong>{{ $coach->name }}</strong><br><small>{{ $coach->email }}{{ $coach->phone ? ' &middot; '.$coach->phone : '' }}</small></td><td>{{ $coach->specialty }}</td><td>{{ $coach->sport?->name ?? 'Unassigned' }}</td><td>{{ $coach->coach_type }}</td><td>{{ $coach->sport?->athletes_count ?? 0 }}</td><td>{{ $coach->events_count }}</td><td><span class="badge coach-status-{{ strtolower($coach->status) }}">{{ $coach->status }}</span></td><td><div class="coach-actions"><a class="text-link" href="{{ route('coaches.show', $coach) }}">View</a><a class="text-link" href="{{ route('coaches.edit', $coach) }}">Edit</a><form method="POST" action="{{ route('coaches.destroy', $coach) }}" onsubmit="return confirm('Are you sure you want to delete this coach?');">@csrf @method('DELETE')<button class="text-link text-button" type="submit">Delete</button></form></div></td></tr>@empty<tr><td colspan="8" class="empty-cell"><strong>{{ request()->hasAny(['search', 'sport_id', 'coach_type', 'status']) ? 'No coaches match your search or filters.' : 'No coaches registered yet.' }}</strong>@if (request()->hasAny(['search', 'sport_id', 'coach_type', 'status']))<br><a class="button button-muted" href="{{ route('coaches.index') }}">Reset Filters</a>@else<br><a class="button" href="{{ route('coaches.create') }}">+ Add Coach</a>@endif</td></tr>@endforelse</tbody></table></div>
@endsection
