@extends('layouts.portal')

@section('content')
<div class="module-header"><div><h1>{{ $sport->name }}</h1><p class="page-subtitle">Sports Management / Sport Details</p></div><div class="event-header-actions"><a class="button button-secondary" href="{{ route('sports.index') }}">Back</a><a class="button" href="{{ route('sports.edit', $sport) }}">Edit Sport</a></div></div>
<section class="card sport-detail-hero"><div><span class="badge sport-status-{{ strtolower($sport->status) }}">{{ $sport->status }}</span><h2>{{ $sport->name }}</h2><p>{{ $sport->description }}</p><small>{{ $sport->classification }}</small></div></section>
<div class="grid sports-detail-stats"><div class="card stat"><small>Athletes</small><strong>{{ $sport->athletes_count }}</strong><a class="text-link" href="{{ route('athletes.index') }}">View athletes &rarr;</a></div><div class="card stat"><small>Coaches</small><strong>{{ $sport->coaches_count }}</strong><a class="text-link" href="{{ route('coaches.index') }}">View coaches &rarr;</a></div><div class="card stat"><small>Events</small><strong>{{ $sport->events_count }}</strong><a class="text-link" href="{{ route('events.index', ['sport_id' => $sport->id]) }}">View events &rarr;</a></div><div class="card stat"><small>Applications</small><strong>{{ $sport->applications_count }}</strong><a class="text-link" href="{{ route('admin.applications', ['sport_id' => $sport->id]) }}">View applications &rarr;</a></div></div>
<section class="sports-detail-columns"><div class="card"><div class="section-heading"><div><h2>Registered Athletes</h2><p class="meta">Athletes currently assigned to this sport.</p></div><a class="text-link" href="{{ route('athletes.index') }}">View all &rarr;</a></div>@forelse ($sport->athletes as $athlete)<div class="related-row"><span><strong>{{ $athlete->name }}</strong><small>{{ $athlete->student_id ?: 'No student ID' }} &middot; {{ $athlete->sport?->name ?? $sport->name }}</small></span></div>@empty<p class="empty-state">No athletes are assigned to this sport.</p>@endforelse</div><div class="card"><div class="section-heading"><div><h2>Assigned Coaches</h2><p class="meta">Coaches linked to this sport.</p></div><a class="text-link" href="{{ route('coaches.index') }}">View all &rarr;</a></div>@forelse ($sport->coaches as $coach)<div class="related-row"><span><strong>{{ $coach->name }}</strong><small>{{ $coach->specialty }}</small></span></div>@empty<p class="empty-state">No coaches are assigned to this sport.</p>@endforelse</div></section>
<section class="card sports-detail-events"><div class="section-heading"><div><h2>Upcoming Events</h2><p class="meta">Scheduled activities for {{ $sport->name }}.</p></div><a class="text-link" href="{{ route('events.index', ['sport_id' => $sport->id]) }}">View all &rarr;</a></div>@forelse ($sport->events as $event)<a class="related-event-row" href="{{ route('events.show', $event) }}"><span><strong>{{ $event->title }}</strong><small>{{ $event->starts_at->format('M j, Y g:i A') }} &middot; {{ $event->venue }}</small></span><span class="badge event-status-{{ strtolower(str_replace(' ', '-', $event->status)) }}">{{ $event->status }}</span></a>@empty<p class="empty-state">No upcoming events for this sport.</p>@endforelse</section>
<section class="card sports-detail-events"><div class="section-heading"><div><h2>Recent Applications</h2><p class="meta">Applications associated with {{ $sport->name }}.</p></div><a class="text-link" href="{{ route('admin.applications', ['sport_id' => $sport->id]) }}">View all &rarr;</a></div>@forelse ($sport->applications as $application)<a class="related-event-row" href="{{ route('applications.show', $application) }}"><span><strong>{{ $application->name }}</strong><small>{{ $application->created_at?->format('M j, Y') }} &middot; {{ $application->email }}</small></span><span class="badge application-status-{{ strtolower(str_replace(' ', '-', $application->status)) }}">{{ $application->status }}</span></a>@empty<p class="empty-state">No applications are associated with this sport.</p>@endforelse</section>
+@endsection
