<?php

namespace App\Http\Controllers;

use App\Models\Application;
use App\Models\Attendance;
use App\Models\AttendanceSession;
use App\Models\Coach;
use App\Models\Event;
use App\Models\Sport;
use App\Models\User;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;
use Illuminate\View\View;
use Symfony\Component\HttpFoundation\Response;

/**
 * Sports Management Reporting Center.
 *
 * Every report is generated straight from the live tables with the same
 * relationships the management modules use, so a report always reflects the
 * database - never a paginated admin page and never hard-coded numbers.
 */
class ReportController extends Controller
{
    public const REPORTS = ['athletes', 'attendance', 'coaches', 'athlete-summary'];

    public const SCHOOL = 'SURIGAO DEL NORTE NATIONAL HIGH SCHOOL';

    public const HUB = 'SPORTSHUB';

    public function index(Request $request): View
    {
        $this->ensureAdministrator();

        $report = $this->reportKey($request);
        $filters = $report ? $this->validateFilters($report, $request) : [];
        $payload = $report ? $this->payload($report, $filters) : null;

        return view('admin.page', array_merge($this->portalData(), [
            'page' => 'reports',
            'heading' => 'Reports',
            'subtitle' => 'Generate and manage official SportsHub reports.',
            'report' => $report,
            'reportPayload' => $payload,
            'filters' => $filters,
            'overview' => $this->overview(),
            'filterOptions' => $report ? $this->filterOptions($report, $filters) : [],
            'generatedAt' => now(),
            'generatedBy' => auth()->user()?->name ?? 'Administrator',
        ]));
    }

    public function export(Request $request): Response
    {
        $this->ensureAdministrator();

        $validated = $request->validate([
            'format' => ['required', 'in:csv,pdf'],
            'report' => ['nullable', 'in:'.implode(',', self::REPORTS)],
        ]);

        $report = $this->reportKey($request) ?? 'attendance';
        $filters = $this->validateFilters($report, $request);
        $payload = $this->payload($report, $filters);
        $filename = $this->filename($report, $filters, $validated['format'] === 'pdf' ? 'pdf' : 'csv');

        if ($validated['format'] === 'pdf') {
            return Pdf::loadView('admin.reports.pdf', [
                'payload' => $payload,
                'generatedAt' => now(),
                'generatedBy' => auth()->user()?->name ?? 'Administrator',
            ])->setPaper('a4', 'landscape')->download($filename);
        }

        return response()->streamDownload(function () use ($payload) {
            $handle = fopen('php://output', 'w');

            fputcsv($handle, [self::SCHOOL]);
            fputcsv($handle, [self::HUB]);
            fputcsv($handle, [$payload['title']]);
            fputcsv($handle, []);
            fputcsv($handle, ['Generated Date', now()->format('F j, Y')]);
            fputcsv($handle, ['Generated By', auth()->user()?->name ?? 'Administrator']);
            fputcsv($handle, ['Filters', $payload['filtersLabel']]);
            fputcsv($handle, []);

            foreach ($payload['summary'] as $item) {
                fputcsv($handle, [$item['label'], $item['value']]);
            }

            fputcsv($handle, []);
            fputcsv($handle, array_column($payload['columns'], 'label'));

            foreach ($payload['rows'] as $row) {
                fputcsv($handle, array_map(fn (array $column) => (string) ($row[$column['key']] ?? ''), $payload['columns']));
            }

            fclose($handle);
        }, $filename, ['Content-Type' => 'text/csv; charset=UTF-8']);
    }

    /**
     * Resolves the requested report. The legacy report_type parameter is still
     * accepted so old dashboard links keep working; anything else falls back
     * to the dashboard.
     */
    private function reportKey(Request $request): ?string
    {
        $key = $request->input('report', $request->input('report_type'));

        return is_string($key) && in_array($key, self::REPORTS, true) ? $key : null;
    }

    private function validateFilters(string $report, Request $request): array
    {
        return match ($report) {
            'athletes' => $request->validate([
                'search' => ['nullable', 'string', 'max:100'],
                'sport_id' => ['nullable', 'integer', 'exists:sports,id'],
                'status' => ['nullable', 'in:Active,Inactive'],
                'grade' => ['nullable', 'string', 'max:100'],
                'gender' => ['nullable', 'string', 'max:30'],
                'eligibility' => ['nullable', 'in:Eligible,Not Eligible,Pending'],
            ]),
            'coaches' => $request->validate([
                'search' => ['nullable', 'string', 'max:100'],
                'sport_id' => ['nullable', 'integer', 'exists:sports,id'],
                'status' => ['nullable', 'in:'.implode(',', CoachController::statuses())],
                'coach_type' => ['nullable', 'in:'.implode(',', CoachController::coachTypes())],
            ]),
            'athlete-summary' => $request->validate([
                'sport_id' => ['nullable', 'integer', 'exists:sports,id'],
                'session_id' => ['nullable', 'integer', 'exists:attendance_sessions,id'],
                'athlete_id' => ['nullable', 'integer', 'exists:users,id'],
                'from' => ['nullable', 'date'],
                'to' => ['nullable', 'date', 'after_or_equal:from'],
            ]),
            default => $request->validate([
                'sport_id' => ['nullable', 'integer', 'exists:sports,id'],
                'session_id' => ['nullable', 'integer', 'exists:attendance_sessions,id'],
                'athlete_id' => ['nullable', 'integer', 'exists:users,id'],
                'from' => ['nullable', 'date'],
                'to' => ['nullable', 'date', 'after_or_equal:from'],
                'status' => ['nullable', 'in:'.implode(',', array_merge(config('attendance.record_statuses'), ['Pending']))],
            ]),
        };
    }

    /**
     * Builds the normalized report payload used by the on-screen preview, the
     * CSV stream and the PDF alike, so every format carries the same rows.
     */
    private function payload(string $report, array $filters): array
    {
        [$title, $rows, $summary, $emptyMessage] = match ($report) {
            'athletes' => $this->athleteReport($filters),
            'coaches' => $this->coachReport($filters),
            'athlete-summary' => $this->athleteAttendanceReport($filters),
            default => $this->attendanceReport($filters),
        };

        return [
            'key' => $report,
            'title' => $title,
            'columns' => $this->columns($report),
            'rows' => $rows->values(),
            'summary' => $summary,
            'filtersLabel' => $this->filtersLabel($report, $filters),
            'emptyMessage' => $emptyMessage,
        ];
    }

    /**
     * Complete athlete list: every Student account matching the filters, with
     * the sport and coach relationships Athlete Management displays.
     */
    private function athleteReport(array $filters): array
    {
        $athletes = User::query()
            ->where('role', 'Student')
            ->with(['sport.coaches', 'applications' => fn ($query) => $query->orderByDesc('created_at')->orderByDesc('id')])
            ->athleteFilters($filters)
            ->orderBy('name')
            ->get()
            ->values()
            ->map(function (User $athlete, int $index) {
                $application = $athlete->applications->first();

                return [
                    'no' => $index + 1,
                    'student_id' => $athlete->student_id ?: 'Not provided',
                    'name' => $athlete->name,
                    'sport' => $athlete->sport?->name ?? 'Unassigned',
                    'coach' => $athlete->sport?->coaches->pluck('name')->join(', ') ?: 'Unassigned',
                    'email' => $athlete->email ?: 'Not provided',
                    'sex' => $application?->gender ?: 'Not provided',
                    'grade_level' => $athlete->gradeLevel() ?: 'Not provided',
                    'phone' => $athlete->phone ?: 'Not provided',
                    'registered' => $athlete->created_at?->format('M j, Y') ?? '—',
                    'status' => $athlete->status ?? 'Active',
                ];
            });

        return [
            'OFFICIAL ATHLETE LIST',
            $athletes,
            [
                ['label' => 'Total Athletes', 'value' => $athletes->count()],
                ['label' => 'Active', 'value' => $athletes->where('status', 'Active')->count()],
                ['label' => 'Inactive', 'value' => $athletes->where('status', 'Inactive')->count()],
                ['label' => 'Sports Represented', 'value' => $athletes->pluck('sport')->filter()->unique()->count()],
            ],
            'No athletes found.',
        ];
    }

    /**
     * Complete coach list, with the sport each coach handles.
     */
    private function coachReport(array $filters): array
    {
        $coaches = Coach::query()
            ->with('sport')
            ->coachFilters($filters)
            ->orderBy('name')
            ->get()
            ->values()
            ->map(function (Coach $coach, int $index) {
                return [
                    'no' => $index + 1,
                    'name' => $coach->name,
                    'sport' => $coach->sport?->name ?? 'Unassigned',
                    'coach_type' => $coach->coach_type ?: 'Not assigned',
                    'specialty' => $coach->specialty ?: 'Not provided',
                    'email' => $coach->email ?: 'Not provided',
                    'phone' => $coach->phone ?: 'Not provided',
                    'status' => $coach->status ?? 'Active',
                    'added' => $coach->created_at?->format('M j, Y') ?? '—',
                ];
            });

        return [
            'OFFICIAL COACH LIST',
            $coaches,
            [
                ['label' => 'Total Coaches', 'value' => $coaches->count()],
                ['label' => 'Active', 'value' => $coaches->where('status', 'Active')->count()],
                ['label' => 'Head Coaches', 'value' => $coaches->where('coach_type', 'Head Coach')->count()],
                ['label' => 'Sports Covered', 'value' => $coaches->pluck('sport')->filter()->unique()->count()],
            ],
            'No coaches found.',
        ];
    }

    /**
     * Every attendance record matching the filters. Pending rows are shown but
     * stay out of the rate, following the existing attendance business rules.
     */
    private function attendanceReport(array $filters): array
    {
        $query = $this->attendanceQuery($filters);

        $records = (clone $query)
            ->orderBy('attended_on')
            ->orderBy('id')
            ->get()
            ->values()
            ->map(function (Attendance $record, int $index) {
                return [
                    'no' => $index + 1,
                    'date' => $record->attended_on?->format('M j, Y') ?? '—',
                    'athlete' => $record->athlete?->name ?? '—',
                    'student_id' => $record->athlete?->student_id ?: 'Not provided',
                    'sport' => $record->sportName(),
                    'activity' => $record->displayName(),
                    'time' => $this->sessionTime($record),
                    'status' => $record->status,
                    'check_in' => $record->check_in_time?->format('g:i A') ?? '—',
                ];
            });

        $summary = $this->attendanceSummary($query);

        return [
            'ATTENDANCE REPORT',
            $records,
            $summary['tiles'],
            'No attendance records found for the selected criteria.',
        ];
    }

    /**
     * Attendance performance per athlete. Rates follow the same rule used by
     * the student portal: Present and Late over counted records only, with
     * pending rows and cancelled sessions excluded. Zero records never divide.
     */
    private function athleteAttendanceReport(array $filters): array
    {
        $counted = (clone $this->attendanceQuery($filters))
            ->counted()
            ->selectRaw('user_id, status, COUNT(*) as total')
            ->groupBy('user_id', 'status')
            ->get();

        $byAthlete = $counted->groupBy('user_id');

        $athletes = User::query()
            ->where('role', 'Student')
            ->when(! empty($filters['athlete_id']), fn ($query) => $query->whereKey($filters['athlete_id']))
            ->when(! empty($filters['sport_id']), fn ($query) => $query->where('sport_id', $filters['sport_id']))
            ->with('sport')
            ->orderBy('name')
            ->get()
            ->values();

        $rows = $athletes->map(function (User $athlete, int $index) use ($byAthlete) {
            $statuses = $byAthlete->get($athlete->id, collect());
            $present = (int) $statuses->firstWhere('status', 'Present')?->total ?? 0;
            $late = (int) $statuses->firstWhere('status', 'Late')?->total ?? 0;
            $absent = (int) $statuses->firstWhere('status', 'Absent')?->total ?? 0;
            $excused = (int) $statuses->firstWhere('status', 'Excused')?->total ?? 0;
            $total = $present + $late + $absent + $excused;

            return [
                'no' => $index + 1,
                'name' => $athlete->name,
                'student_id' => $athlete->student_id ?: 'Not provided',
                'sport' => $athlete->sport?->name ?? 'Unassigned',
                'present' => $present,
                'late' => $late,
                'absent' => $absent,
                'excused' => $excused,
                'total' => $total,
                'rate' => $total > 0 ? round((($present + $late) / $total) * 100, 1) : 0.0,
            ];
        });

        $summary = $this->attendanceSummary($this->attendanceQuery($filters));

        return [
            'ATHLETE ATTENDANCE SUMMARY',
            $rows,
            $summary['tiles'],
            'No athletes found.',
        ];
    }

    /**
     * The shared attendance query. Sport, session, athlete, date range and
     * status filters reuse the scopes Attendance Management already relies on.
     */
    private function attendanceQuery(array $filters): Builder
    {
        return Attendance::query()
            ->with(['athlete.sport', 'session.sport', 'event.sport'])
            ->when($filters['sport_id'] ?? null, function ($query, $sportId) {
                $query->where(function ($nested) use ($sportId) {
                    $nested->whereHas('athlete', fn ($athletes) => $athletes->where('sport_id', $sportId))
                        ->orWhereHas('session', fn ($sessionQuery) => $sessionQuery->forSport((int) $sportId));
                });
            })
            ->when($filters['session_id'] ?? null, fn ($query, $sessionId) => $query->forSession((int) $sessionId))
            ->when($filters['athlete_id'] ?? null, fn ($query, $athleteId) => $query->where('user_id', $athleteId))
            ->when($filters['from'] ?? null, fn ($query, $from) => $query->whereDate('attended_on', '>=', $from))
            ->when($filters['to'] ?? null, fn ($query, $to) => $query->whereDate('attended_on', '<=', $to))
            ->when($filters['status'] ?? null, fn ($query, $status) => $query->where('status', $status));
    }

    /**
     * Counted attendance totals for the filtered set. Uses the model's counted
     * scope so Pending rows and cancelled sessions stay out of the rate.
     */
    private function attendanceSummary(Builder $query): array
    {
        $counts = (clone $query)
            ->counted()
            ->selectRaw('status, COUNT(*) as total')
            ->groupBy('status')
            ->pluck('total', 'status');

        $present = (int) $counts->get('Present', 0);
        $late = (int) $counts->get('Late', 0);
        $absent = (int) $counts->get('Absent', 0);
        $excused = (int) $counts->get('Excused', 0);
        $countedTotal = $present + $late + $absent + $excused;
        $pending = (int) (clone $query)->where('status', 'Pending')->count();
        $rate = $countedTotal > 0 ? round((($present + $late) / $countedTotal) * 100, 1) : 0.0;

        return [
            'present' => $present,
            'late' => $late,
            'absent' => $absent,
            'excused' => $excused,
            'pending' => $pending,
            'counted_total' => $countedTotal,
            'rate' => $rate,
            'tiles' => [
                ['label' => 'Total Records', 'value' => $countedTotal + $pending],
                ['label' => 'Present', 'value' => $present],
                ['label' => 'Late', 'value' => $late],
                ['label' => 'Absent', 'value' => $absent],
                ['label' => 'Excused', 'value' => $excused],
                ['label' => 'Pending (not counted)', 'value' => $pending],
                ['label' => 'Attendance Rate', 'value' => $rate.'%'],
            ],
        ];
    }

    private function sessionTime(Attendance $record): string
    {
        if ($record->session?->start_time) {
            return Carbon::parse($record->session->start_time)->format('g:i A');
        }

        if ($record->event?->starts_at) {
            return $record->event->starts_at->format('g:i A');
        }

        return '—';
    }

    private function columns(string $report): array
    {
        return match ($report) {
            'athletes' => [
                ['key' => 'no', 'label' => '#'],
                ['key' => 'student_id', 'label' => 'Student ID'],
                ['key' => 'name', 'label' => 'Athlete Name'],
                ['key' => 'sport', 'label' => 'Sport'],
                ['key' => 'coach', 'label' => 'Coach'],
                ['key' => 'email', 'label' => 'Email'],
                ['key' => 'sex', 'label' => 'Sex'],
                ['key' => 'grade_level', 'label' => 'Year Level'],
                ['key' => 'phone', 'label' => 'Contact Number'],
                ['key' => 'registered', 'label' => 'Date Registered'],
                ['key' => 'status', 'label' => 'Status'],
            ],
            'coaches' => [
                ['key' => 'no', 'label' => '#'],
                ['key' => 'name', 'label' => 'Coach Name'],
                ['key' => 'sport', 'label' => 'Sport'],
                ['key' => 'coach_type', 'label' => 'Coach Type'],
                ['key' => 'specialty', 'label' => 'Specialization'],
                ['key' => 'email', 'label' => 'Email'],
                ['key' => 'phone', 'label' => 'Contact'],
                ['key' => 'status', 'label' => 'Status'],
                ['key' => 'added', 'label' => 'Date Added'],
            ],
            'athlete-summary' => [
                ['key' => 'no', 'label' => '#'],
                ['key' => 'name', 'label' => 'Athlete'],
                ['key' => 'student_id', 'label' => 'Student ID'],
                ['key' => 'sport', 'label' => 'Sport'],
                ['key' => 'present', 'label' => 'Present'],
                ['key' => 'late', 'label' => 'Late'],
                ['key' => 'absent', 'label' => 'Absent'],
                ['key' => 'excused', 'label' => 'Excused'],
                ['key' => 'total', 'label' => 'Total Records'],
                ['key' => 'rate', 'label' => 'Attendance Rate'],
            ],
            default => [
                ['key' => 'no', 'label' => '#'],
                ['key' => 'date', 'label' => 'Date'],
                ['key' => 'athlete', 'label' => 'Athlete'],
                ['key' => 'student_id', 'label' => 'Student ID'],
                ['key' => 'sport', 'label' => 'Sport'],
                ['key' => 'activity', 'label' => 'Attendance Event'],
                ['key' => 'time', 'label' => 'Time'],
                ['key' => 'status', 'label' => 'Status'],
                ['key' => 'check_in', 'label' => 'Check-in'],
            ],
        };
    }

    /**
     * Human readable list of the filters a generated report was built with, so
     * printed and downloaded copies stay understandable later.
     */
    private function filtersLabel(string $report, array $filters): string
    {
        $labels = collect();

        if (! empty($filters['search'])) {
            $labels->push('Search: '.$filters['search']);
        }
        if (! empty($filters['sport_id'])) {
            $labels->push('Sport: '.(Sport::find($filters['sport_id'])?->name ?? '—'));
        }
        if (! empty($filters['status'])) {
            $labels->push('Status: '.$filters['status']);
        }
        if (! empty($filters['grade'])) {
            $labels->push('Year Level: '.$filters['grade']);
        }
        if (! empty($filters['gender'])) {
            $labels->push('Sex: '.$filters['gender']);
        }
        if (! empty($filters['eligibility'])) {
            $labels->push('Eligibility: '.$filters['eligibility']);
        }
        if (! empty($filters['coach_type'])) {
            $labels->push('Coach Type: '.$filters['coach_type']);
        }
        if (! empty($filters['session_id'])) {
            $labels->push('Session: '.(AttendanceSession::find($filters['session_id'])?->displayName() ?? '—'));
        }
        if (! empty($filters['athlete_id'])) {
            $labels->push('Athlete: '.(User::find($filters['athlete_id'])?->name ?? '—'));
        }
        if (! empty($filters['from'])) {
            $labels->push('Date From: '.Carbon::parse($filters['from'])->format('F j, Y'));
        }
        if (! empty($filters['to'])) {
            $labels->push('Date To: '.Carbon::parse($filters['to'])->format('F j, Y'));
        }

        return $labels->isNotEmpty() ? $labels->implode(' · ') : 'All';
    }

    /**
     * Sanitized, meaningful download name: report slug, optional sport or date
     * range, and the generation date. User input is never used verbatim.
     */
    private function filename(string $report, array $filters, string $extension): string
    {
        $parts = [match ($report) {
            'athletes' => 'athlete-list',
            'coaches' => 'coach-list',
            'athlete-summary' => 'athlete-attendance-summary',
            default => 'attendance-report',
        }];

        if (! empty($filters['sport_id']) && $sport = Sport::find($filters['sport_id'])) {
            $parts[] = $sport->name;
        }

        if (! empty($filters['from']) && ! empty($filters['to'])) {
            $parts[] = $filters['from'].'-to-'.$filters['to'];
        } elseif (! empty($filters['from'])) {
            $parts[] = 'from-'.$filters['from'];
        } elseif (! empty($filters['to'])) {
            $parts[] = 'to-'.$filters['to'];
        }

        $parts[] = now()->toDateString();

        $slug = collect($parts)
            ->map(fn ($part) => Str::slug((string) $part))
            ->filter()
            ->implode('-');

        return Str::limit($slug, 180, '').'.'.$extension;
    }

    private function overview(): array
    {
        $counts = Attendance::query()
            ->counted()
            ->selectRaw('status, COUNT(*) as total')
            ->groupBy('status')
            ->pluck('total', 'status');

        $countedTotal = (int) $counts->sum();
        $rate = $countedTotal > 0
            ? round((((int) $counts->get('Present', 0)) + ((int) $counts->get('Late', 0))) / $countedTotal * 100, 1)
            : 0.0;

        return [
            ['label' => 'Total Athletes', 'value' => User::where('role', 'Student')->count()],
            ['label' => 'Total Coaches', 'value' => Coach::count()],
            ['label' => 'Total Sports', 'value' => Sport::count()],
            ['label' => 'Total Events', 'value' => Event::count()],
            ['label' => 'Attendance Records', 'value' => Attendance::count()],
            ['label' => 'Attendance Rate', 'value' => $rate.'%'],
        ];
    }

    /**
     * Dropdown data for the active report's filter panel only, so the
     * dashboard itself stays cheap to render.
     */
    private function filterOptions(string $report, array $filters): array
    {
        $options = ['sports' => Sport::orderBy('name')->get()];

        if ($report === 'athletes') {
            $options['grades'] = Application::whereNotNull('grade')->distinct()->orderBy('grade')->pluck('grade');
            $options['genders'] = Application::whereNotNull('gender')->distinct()->orderBy('gender')->pluck('gender');
            $options['statuses'] = ['Active', 'Inactive'];
        }

        if ($report === 'coaches') {
            $options['statuses'] = CoachController::statuses();
            $options['coachTypes'] = CoachController::coachTypes();
        }

        if (in_array($report, ['attendance', 'athlete-summary'], true)) {
            $options['recordStatuses'] = array_merge(config('attendance.record_statuses'), ['Pending']);
            $options['sessions'] = AttendanceSession::query()
                ->with('sport')
                ->orderByDesc('session_date')
                ->orderByDesc('id')
                ->limit(200)
                ->get()
                ->map(fn (AttendanceSession $session) => [
                    'id' => $session->id,
                    'label' => $session->displayName().' — '.$session->session_date?->format('M j, Y').' ('.$session->effectiveSportName().')',
                ]);
            $options['athletes'] = User::query()
                ->where('role', 'Student')
                ->when(! empty($filters['sport_id']), fn ($query) => $query->where('sport_id', $filters['sport_id']))
                ->orderBy('name')
                ->get(['id', 'name', 'student_id'])
                ->map(fn (User $athlete) => [
                    'id' => $athlete->id,
                    'label' => $athlete->name.($athlete->student_id ? ' ('.$athlete->student_id.')' : ''),
                ]);
        }

        return $options;
    }

    private function portalData(): array
    {
        return [
            'title' => 'Reports',
            'navItems' => [
                ['key' => 'dashboard', 'label' => 'Dashboard', 'icon' => 'dashboard', 'route' => 'dashboard'],
                ['key' => 'events', 'label' => 'Events', 'icon' => 'calendar', 'route' => 'events.index'],
                ['key' => 'calendar', 'label' => 'Calendar', 'icon' => 'calendar', 'route' => 'admin.calendar'],
                ['key' => 'applications', 'label' => 'Applications', 'icon' => 'clipboard', 'route' => 'admin.applications'],
                ['key' => 'sports', 'label' => 'Sports', 'icon' => 'trophy', 'route' => 'sports.index'],
                ['key' => 'athletes', 'label' => 'Athletes', 'icon' => 'activity', 'route' => 'athletes.index'],
                ['key' => 'medical', 'label' => 'Medical', 'icon' => 'medical', 'route' => 'admin.medical'],
                ['key' => 'coaches', 'label' => 'Coaches', 'icon' => 'users', 'route' => 'coaches.index'],
                ['key' => 'attendance', 'label' => 'Attendance', 'icon' => 'clipboard', 'route' => 'admin.attendance'],
                ['key' => 'announcements', 'label' => 'Announcements', 'icon' => 'megaphone', 'route' => 'admin.announcements'],
                ['key' => 'achievements', 'label' => 'Achievements', 'icon' => 'trophy', 'route' => 'admin.achievements'],
                ['key' => 'reports', 'label' => 'Reports', 'icon' => 'chart', 'route' => 'reports.index'],
            ],
            'active' => 'reports',
            'roleLabel' => 'Admin Portal',
            'userName' => auth()->user()?->name ?? 'Admin User',
            'userRole' => auth()->user()?->role ?? 'Administrator',
        ];
    }

    private function ensureAdministrator(): void
    {
        abort_unless(auth()->user()?->role === 'Administrator', 403);
    }
}
